import { test, expect } from '@playwright/test';
import {login} from "./utils/auth";
test('test', async ({ page }) => {
  await login(page);
  await page.getByRole('link', { name: 'Rechnungen' }).click();
  await page.getByRole('link', { name: '[✓] Rechnung' }).click();
  await page.getByText('Rechnung Rechnungskreis R-%').click();
  await page.locator('input[name="dto[offerNumber]"]').click();
  await page.locator('input[name="dto[offerNumber]"]').fill('12345');
  await page.locator('input[name="dto[orderNumber]"]').click();
  await page.locator('input[name="dto[orderNumber]"]').fill('56789');
  await page.locator('input[name="dto[customerNumber]"]').click();
  await page.locator('input[name="dto[customerNumber]"]').fill('10019');
  await page.getByRole('button', { name: '[✓] Speichern' }).click();
  await expect(page.locator('input[name="object[title]"]')).toHaveValue('Rechnung');
  await expect(page.locator('input[name="object[subTitle]"]')).toBeEmpty();
  await expect(page.getByRole('paragraph')).toContainText('Für die nachfolgende aufgeführten Leistungen berechnen wir Ihnen analog zum Angebot Nr. {invoice.offerNumber} und den Allgemeinen Geschäftsbedingungen (Stand: Oktober 2024)');
  await page.getByRole('tab', { name: 'Auftrag' }).click();
  await expect(page.locator('input[name="object[offerNumber]"]')).toHaveValue('12345');
  await expect(page.locator('input[name="object[order][orderNumber]"]')).toHaveValue('56789');
  await expect(page.locator('input[name="object[order][customerReference]"]')).toBeEmpty();
  await page.locator('input[name="object[order][customerReference]"]').click();
  await page.locator('input[name="object[order][customerReference]"]').fill('Projektname');
  await page.locator('input[name="object[order][commissioningDate][date]"]').fill('2021-10-10');
  await page.getByRole('button', { name: '[✓] Speichern' }).click();
  await page.getByRole('tab', { name: 'Kunde' }).click();
  await expect(page.locator('input[name="object[customer][deptorNumber]"]')).toHaveValue('10019');
  await expect(page.locator('input[name="object[customer][name]"]')).toHaveValue('Deutsches Rotes Kreuz Bildungswerk Sachsen gGmbH');
  await expect(page.getByText('Deutsches Rotes Kreuz')).toHaveValue('Deutsches Rotes Kreuz Bildungswerk Sachsen gGmbH\nBremer Straße 10d\n01067 Dresden - Deutschland (DE)');
  await page.getByRole('tab', { name: 'Zusatztexte' }).click();
  await page.getByRole('tab', { name: 'Statusinformationen' }).click();
  await page.getByRole('button', { name: 'Rechnungsposition hinzufügen' }).click();
  await page.locator('input[name="object[invoiceItems][0][articleReference]"]').click();
  await page.locator('input[name="object[invoiceItems][0][articleReference]"]').fill('100');
  await page.locator('input[name="object[invoiceItems][0][articleReference]"]').press('Tab');
  await page.locator('input[name="object[invoiceItems][0][name]"]').fill('Testartikel');
  await page.locator('input[name="object[invoiceItems][0][name]"]').press('Tab');
  await page.getByText('Anzahl Artikel Pauschale Pcs Stunde Stück PcsRemove item').click();
  await page.getByRole('option', { name: 'Anzahl Artikel Press to select' }).click();
  await page.locator('.form-control.currency-input-field').first().click();
  await page.locator('.form-control.currency-input-field').first().fill('1000,00');
  await page.getByRole('button', { name: '[✓] Speichern' }).click();
  await expect(page.locator('td:nth-child(8) > .form-group > fucodo-form-currency > .currency-input-wrapper > .form-control')).toHaveValue('1.000,00');
  await expect(page.locator('.text-end > .form-group > fucodo-form-currency > .currency-input-wrapper > .form-control').first()).toHaveValue('1.000,00');
  await expect(page.locator('tr:nth-child(2) > td:nth-child(2) > .form-group > fucodo-form-currency > .currency-input-wrapper > .form-control')).toHaveValue('190,00');
  await expect(page.locator('th:nth-child(2) > .form-group > fucodo-form-currency > .currency-input-wrapper > .form-control')).toHaveValue('1.190,00');

});
