<?php
namespace KayStrobach\Invoice\Domain\Model;

/*
 * This file is part of the KayStrobach.Invoice package.
 */

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use KayStrobach\Invoice\Domain\Model\Invoice\BankTransferDocument;
use KayStrobach\Invoice\Domain\Model\Invoice\Embeddable\CustomerEmbeddable;
use KayStrobach\Invoice\Domain\Model\Invoice\Embeddable\MoneyEmbeddable;
use KayStrobach\Invoice\Domain\Model\Invoice\Embeddable\NumberingEmbeddable;
use KayStrobach\Invoice\Domain\Model\Invoice\Embeddable\OptionsEmbeddable;
use KayStrobach\Invoice\Domain\Model\Invoice\Embeddable\OrderEmbeddable;
use KayStrobach\Invoice\Domain\Model\Invoice\Embeddable\PeriodEmbeddable;
use KayStrobach\Invoice\Domain\Model\Invoice\Embeddable\SellerEmbeddable;
use KayStrobach\Invoice\Domain\Model\Invoice\TaxRecord;
use KayStrobach\Invoice\Domain\Repository\InvoiceRepository;
use KayStrobach\Invoice\Domain\Traits\CollectionBugfixTrait;
use KayStrobach\Invoice\Service\AddressEmbeddableConversionService;
use KayStrobach\Invoice\Service\CreateInvoicePdfService;
use KayStrobach\ObosTrainsWsd\AutogeneratedCode\BuchungUndStorno\StructType\Tax;
use KayStrobach\Ota\Domain\Model\Booking\Documents\AutogeneratedDocument;
use KayStrobach\Tags\Domain\Model\TagableTrait;
use Neos\Flow\Annotations as Flow;
use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Mvc\Controller\ControllerContext;
use Neos\Flow\ResourceManagement\PersistentResource;

/**
 * @Flow\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\HasLifecycleCallbacks()
 */
class Invoice
{
    use CollectionBugfixTrait;
    use TagableTrait;

    /**
     * @ORM\Embedded(columnPrefix="number_")
     */
    protected ?NumberingEmbeddable $number = null;

    /**
     * @ORM\Column(nullable=true)
     * @var string
     */
    protected $title = 'Rechnung';

    /**
     * @ORM\Column(nullable=true)
     * @var string
     */
    protected $subTitle;

    /**
     * @ORM\Column(nullable=true, type="text")
     * @var string
     */
    protected $deliveryAuditInformation;

    /**
     * @var string
     */
    protected $currency = '€';

    /**
     * @ORM\Embedded(columnPrefix="customer_")
     * @var CustomerEmbeddable
     */
    protected CustomerEmbeddable $customer;

    /**
     * @ORM\Embedded(columnPrefix="seller_")
     * @var SellerEmbeddable
     */
    protected SellerEmbeddable $seller;

    /**
     * @var string
     * @Flow\Validate(type="text")
     * @ORM\Column(type="text", length=65532, nullable=true)
     */
    protected $additionalInformation;

    /**
     * @var string
     */
    protected string $offerNumber = '';

    /**
     * @var DateTime
     */
    protected $date;

    /**
     * @var string
     */
    protected $year;

    /**
     * @ORM\Embedded(columnPrefix="period_of_performance_")
     * @var PeriodEmbeddable
     */
    protected PeriodEmbeddable $periodOfPerformance;

    /**
     * @ORM\Embedded(columnPrefix="order_")
     * @var OrderEmbeddable
     */
    protected OrderEmbeddable $order;

    /**
     * @var string
     * @Flow\Validate(type="text")
     * @ORM\Column(type="text", length=65532, nullable=true)
     */
    protected $preText;

    /**
     * @var string
     * @Flow\Validate(type="text")
     * @ORM\Column(type="text", length=65532, nullable=true)
     */
    protected $postText;

    /**
     * @var string
     * @Flow\Validate(type="text")
     * @ORM\Column(type="text", length=65532, nullable=true)
     */
    protected $additionalText;

    /**
     * @ORM\OrderBy({"sort":"ASC"})
     * @ORM\OneToMany(cascade={"all"}, mappedBy="invoice")
     * @var \Doctrine\Common\Collections\ArrayCollection<\KayStrobach\Invoice\Domain\Model\InvoiceItem>
     */
    protected $invoiceItems;

    /**
     * @ORM\OneToMany(cascade={"all"}, mappedBy="invoice")
     * @ORM\OrderBy({"dueDate" = "ASC"})
     * @var \Doctrine\Common\Collections\ArrayCollection<\KayStrobach\Invoice\Domain\Model\SettlementDate>
     */
    protected $settlementDates;

    /**
     * @var @ORM\OneToMany(cascade={"all"}, mappedBy="invoice")
     * @var @ORM\OrderBy({"dueDate" = "ASC", "account"="DESC", "offsetAccount"="DESC"})
     * @var \Doctrine\Common\Collections\ArrayCollection<\KayStrobach\Invoice\Domain\Model\AccountingRecord>
     */
    protected $accountingRecords;

    /**
     * @var bool
     */
    protected $changeable = true;

    /**
     * @var PersistentResource
     * @ORM\OneToOne(cascade={"all"})
     */
    protected $originalResource;

    /**
     * @ORM\OneToMany(orphanRemoval=true, cascade={"all"}, mappedBy="invoice")
     * @ORM\OrderBy({"creationDate" = "ASC"})
     * @var Collection<BankTransferDocument>
     */
    protected $bankTransferDocuments;

    /**
     * @ORM\Embedded(columnPrefix="total_")
     * @var MoneyEmbeddable
     */
    protected $total;

    /**
     * @ORM\Embedded(columnPrefix="totalnotaxes_")
     * @var MoneyEmbeddable
     */
    protected $totalNoTaxes;

    /**
     * @ORM\Embedded(columnPrefix="options_")
     * @var OptionsEmbeddable
     */
    protected $options;



    /**
     * @Flow\Inject()
     * @var InvoiceRepository
     */
    protected $invoiceRepository;

    /**
     * @ORM\OneToOne(cascade={"persist"}, inversedBy="originalInvoice")
     * @ORM\Column(nullable=true)
     * @var Invoice
     */
    protected $stornoInvoice;

    /**
     * @ORM\OneToOne(cascade={"persist"}, mappedBy="stornoInvoice")
     * @ORM\Column(nullable=true)
     * @var Invoice
     */
    protected $originalInvoice;

    /**
     * @ORM\OneToMany (mappedBy="invoice", cascade={"all"})
     * @ORM\OrderBy({"taxRate": "ASC"})
     * @var Collection<TaxRecord>
     */
    protected $taxRecords;

    /**
     * @Flow\Inject
     * @var AddressEmbeddableConversionService
     */
    protected AddressEmbeddableConversionService $addressEmbeddableService;

    public function __construct()
    {
        $this->number = new NumberingEmbeddable();
        $this->settlementDates = new ArrayCollection();
        $this->invoiceItems = new ArrayCollection();
        $this->accountingRecords = new ArrayCollection();
        $this->date = new DateTime('now');
        $this->year = $this->date->format('Y');
        $this->periodOfPerformance = new PeriodEmbeddable();
        $this->taxRecords = new ArrayCollection();
        $this->bankTransferDocuments = new ArrayCollection();
        $this->total = new MoneyEmbeddable();
        $this->totalNoTaxes = new MoneyEmbeddable();
        $this->customer = new CustomerEmbeddable();
        $this->seller = new SellerEmbeddable();
        $this->order = new OrderEmbeddable();
        $this->options = new OptionsEmbeddable();
    }

    /**
     * @deprecated
     * @return string
     */
    public function getNumberPrefix()
    {
        return $this->number->getPrefix();
    }

    /**
     * @return NumberingEmbeddable
     */
    public function getNumber(): NumberingEmbeddable
    {
        return $this->number;
    }

    /**
     * @param NumberingEmbeddable $number
     */
    public function setNumber(NumberingEmbeddable $number)
    {
        $this->number = $number;
        $this->number->updateCombinedNumber();
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title ?? '';
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title = null): void
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getSubTitle(): string
    {
        return $this->subTitle ?? '';
    }

    /**
     * @param string $subTitle
     */
    public function setSubTitle(string $subTitle = null): void
    {
        $this->subTitle = $subTitle;
    }

    /**
     * @return string
     */
    public function getDeliveryAuditInformation(): string
    {
        return $this->deliveryAuditInformation ?? '';
    }

    /**
     * @param string $deliveryAuditInformation
     */
    public function setDeliveryAuditInformation(string $deliveryAuditInformation): void
    {
        $this->deliveryAuditInformation = $deliveryAuditInformation;
    }

    /**
     * @return string
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * @param string $year
     */
    public function setYear($year)
    {
        $this->year = $year;
    }

    public function getPeriodOfPerformance(): PeriodEmbeddable
    {
        return $this->periodOfPerformance;
    }

    public function setPeriodOfPerformance(PeriodEmbeddable $periodOfPerformance): void
    {
        $this->periodOfPerformance = $periodOfPerformance;
    }

    public function getOrder(): OrderEmbeddable
    {
        return $this->order;
    }

    public function setOrder(OrderEmbeddable $order): void
    {
        $this->order = $order;
    }

    /**
     * @deprecated
     * @return string
     */
    public function getCurrency()
    {
        return $this->total->getCurrency();
    }

    /**
     * @return string
     */
    public function getPreText(): string
    {
        return $this->preText ?? '';
    }

    /**
     * @param string $preText
     */
    public function setPreText(string $preText = null): void
    {
        $this->preText = $preText;
    }

    /**
     * @return string
     */
    public function getPostText(): string
    {
        return $this->postText ?? '';
    }

    /**
     * @param string $postText
     */
    public function setPostText(string $postText = null): void
    {
        $this->postText = $postText;
    }

    /**
     * @return string
     */
    public function getAdditionalInformation(): ?string
    {
        return $this->additionalInformation;
    }

    /**
     * @param string $additionalInformation
     */
    public function setAdditionalInformation($additionalInformation)
    {
        $this->additionalInformation = $additionalInformation;
    }

    public function getOfferNumber(): string
    {
        return $this->offerNumber;
    }

    public function setOfferNumber(string $offerNumber): void
    {
        $this->offerNumber = $offerNumber;
    }

    /**
     * @return DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param DateTime $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return string
     */
    public function getAdditionalText()
    {
        return $this->additionalText;
    }

    /**
     * @param string $additionalText
     */
    public function setAdditionalText($additionalText)
    {
        $this->additionalText = $additionalText;
    }

    /**
     * @return \Doctrine\Common\Collections\ArrayCollection<\KayStrobach\Invoice\Domain\Model\InvoiceItem>
     */
    public function getInvoiceItems()
    {
        return $this->invoiceItems;
    }

    /**
     * @param \Doctrine\Common\Collections\ArrayCollection<\KayStrobach\Invoice\Domain\Model\InvoiceItem> $invoiceItems
     */
    public function setInvoiceItems($invoiceItems)
    {
        $this->invoiceItems = $this->mergeCollections($this->invoiceItems, $invoiceItems);
    }

    /**
     * @return \Doctrine\Common\Collections\ArrayCollection<\KayStrobach\Invoice\Domain\Model\SettlementDate>
     */
    public function getSettlementDates()
    {
        return $this->settlementDates;
    }

    /**
     * @param \Doctrine\Common\Collections\ArrayCollection<\KayStrobach\Invoice\Domain\Model\SettlementDate> $settlementDates
     */
    public function setSettlementDates($settlementDates)
    {
        $this->settlementDates = $this->mergeCollections($this->settlementDates, $settlementDates);
    }

    public function getSettlementDatesSum()
    {
        $sum = 0;
        /** @var SettlementDate $settlementDate */
        foreach ($this->settlementDates as $settlementDate) {
            $sum += $settlementDate->getAmount();
        }
        return $sum;
    }

    public function markSettlementDatePaidByDate(DateTime $date, $paid)
    {
        /** @var SettlementDate $settlementDate */
        foreach ($this->settlementDates as $settlementDate) {
            if ($settlementDate->getDueDate()->format('Y-m-d') === $date->format('Y-m-d')) {
                $settlementDate->setPaid($paid);
            }
        }

        /** @var AccountingRecord $accountingRecord */
        foreach ($this->accountingRecords as $accountingRecord) {
            if ($accountingRecord->getDueDate() === null) {
                continue;
            }
            if ($accountingRecord->getDueDate()->format('Y-m-d') === $date->format('Y-m-d')) {
                $accountingRecord->setPaid($paid);
            }
        }
    }

    /**
     * @return bool
     */
    public function isChangeable(): ?bool
    {
        return $this->changeable;
    }

    /**
     * @param bool $changeable
     */
    public function setChangeable(bool $changeable = null): void
    {
        $this->changeable = $changeable;
    }

    public function isNotChangeable(): ?bool
    {
        return !$this->isChangeable();
    }

    /**
     * @return PersistentResource
     */
    public function getOriginalResource(): ?PersistentResource
    {
        return $this->originalResource;
    }

    /**
     * @return Collection
     */
    public function getBankTransferDocuments(): Collection
    {
        return $this->bankTransferDocuments;
    }

    /**
     * @param Collection $bankTransferDocuments
     */
    public function setBankTransferDocuments(Collection $bankTransferDocuments): void
    {
        $this->bankTransferDocuments = $bankTransferDocuments;
    }

    /**
     * @return MoneyEmbeddable
     */
    public function getTotal(): MoneyEmbeddable
    {
        return $this->total;
    }

    /**
     * @param MoneyEmbeddable $total
     */
    public function setTotal(MoneyEmbeddable $total): void
    {
        $this->total = $total;
    }

    public function calculateTotal(): ?bool
    {
        if (!$this->isChangeable()) {
            return false;
        }

        $sum = 0;
        /** @var InvoiceItem $invoiceItem */
        foreach ($this->getInvoiceItems() as $invoiceItem) {
            $invoiceItem->calculateTotal();
            $sum += $invoiceItem->getTotal()->getValue();
        }

        $this->getTotalNoTaxes()->setValue($sum);
        $this->updateTaxRecords();

        foreach ($this->taxRecords as $taxRecord) {
            $sum += $taxRecord->getSum()->getValue();
        }
        $this->total->setValue($sum);
        return true;
    }

    /**
     * @param PersistentResource $originalResource
     */
    public function setOriginalResource(PersistentResource $originalResource): void
    {
        $this->originalResource = $originalResource;
    }

    /**
     * @FLow\Inject
     * @var CreateInvoicePdfService
     */
    protected CreateInvoicePdfService $invoicePdfService;

    public function createDocument(ControllerContext $controllerContext = null, bool $hideSinglePrice = false)
    {
        $this->changeable = false;
        $this->invoicePdfService->render($this, $hideSinglePrice);


    }

    public function isPaymentDelayed(): bool
    {
        $now = new DateTime('now');
        $delayed = false;
        /** @var SettlementDate $settlementDate */
        foreach($this->getSettlementDates() as $settlementDate) {
            if (($settlementDate->getDueDate() < $now) && (!$settlementDate->isPaid())) {
                $delayed = true;
                break;
            }
        }
        return $delayed;
    }

    public function isPaid(): bool
    {
        $paid = true;
        /** @var SettlementDate $settlementDate */
        foreach($this->getSettlementDates() as $settlementDate) {
            if (!$settlementDate->isPaid()) {
                $paid = false;
                break;
            }
        }
        return $paid;
    }

    /**
     * @return mixed
     */
    public function getAccountingRecords()
    {
        return $this->accountingRecords;
    }

    /**
     * @param mixed $accountingRecords
     */
    public function setAccountingRecords($accountingRecords): void
    {
        $this->accountingRecords = $accountingRecords;
    }

    /**
     * @return Invoice
     */
    public function getStornoInvoice(): ?Invoice
    {
        return $this->stornoInvoice;
    }

    /**
     * @param Invoice $stornoInvoice
     */
    public function setStornoInvoice(Invoice $stornoInvoice = null): void
    {
        $this->stornoInvoice = $stornoInvoice;
    }

    /**
     * @return Invoice
     */
    public function getOriginalInvoice(): ?Invoice
    {
        return $this->originalInvoice;
    }

    /**
     * @param Invoice $originalInvoice
     */
    public function setOriginalInvoice(Invoice $originalInvoice = null): void
    {
        $this->originalInvoice = $originalInvoice;
    }

    /**
     * @return Collection<TaxRecord>
     */
    public function getTaxRecords(): Collection
    {
        return $this->taxRecords;
    }

    /**
     * @param Collection<TaxRecord> $taxRecords
     */
    public function setTaxRecords(Collection $taxRecords): void
    {
        $this->taxRecords = $taxRecords;
    }

    public function createTaxRecord($sum, $rate): TaxRecord
    {
        $tr = new TaxRecord();
        $tr->setInvoice($this);
        $tr->getSum()->setValue($sum);
        $tr->setTaxRate($rate);
        $this->getTaxRecords()->add($tr);

        return $tr;
    }

    public function updateTaxRecords()
    {
        $taxRecords = [];
        foreach ($this->invoiceItems as $invoiceItem) {
            $tax = (string)round($invoiceItem->getTax(), 2);
            if (($tax === '') || ($tax === '0.00')) {
                continue;
            }
            if (!isset($taxRecords[$tax])) {
                $taxRecords[$tax] = 0;
            }
            $taxRecords[$tax] += $invoiceItem->getTotal()->getValue() * ($tax/100);
            $this->totalNoTaxes->setCurrency($invoiceItem->getTotal()->getCurrency() ?? 'EUR');
        }

        $this->taxRecords->clear();
        foreach ($taxRecords as $rate => $sum) {
            if ($sum !== 0) {
                $this->createTaxRecord($sum, $rate);
            }
        }
    }

    /**
     * @return MoneyEmbeddable
     */
    public function getTotalNoTaxes(): MoneyEmbeddable
    {
        return $this->totalNoTaxes;
    }

    /**
     * @param MoneyEmbeddable $totalNoTaxes
     */
    public function setTotalNoTaxes(MoneyEmbeddable $totalNoTaxes): void
    {
        $this->totalNoTaxes = $totalNoTaxes;
    }

    public function getCustomer(): CustomerEmbeddable
    {
        return $this->customer;
    }

    public function setCustomer(CustomerEmbeddable $customer): void
    {
        $this->customer = $customer;
    }

    public function getSeller(): SellerEmbeddable
    {
        return $this->seller;
    }

    public function setSeller(SellerEmbeddable $seller): void
    {
        $this->seller = $seller;
    }

    /**
     * @param ControllerContext|null $controllerContext
     * @param \Closure|null $callback
     * @return Invoice
     */
    public function makeCancellationInvoice(ControllerContext $controllerContext = null, \Closure $callback = null)
    {
        if ($this->stornoInvoice) {
            return null;
        }
        if ($this->originalInvoice) {
            return null;
        }

        $newTotal = new MoneyEmbeddable();
        $newTotal->setValue($this->total->getValue() * -1);
        $newTotal->setCurrency($this->total->getCurrency());

        $newTotalNoTaxes = new MoneyEmbeddable();
        $newTotalNoTaxes->setValue($this->totalNoTaxes->getValue() * -1);
        $newTotalNoTaxes->setCurrency($this->totalNoTaxes->getCurrency());

        $newInvoice = $this->makePartialClone();
        $newInvoice->setTotal($newTotal);
        $newInvoice->setTotalNoTaxes($newTotalNoTaxes);
        $newInvoice->setTitle('Stornorechnung');
        $newInvoice->setSubTitle('zu ' . $this->getNumber()->getCombinedNumber());

        $this->invoiceRepository->add($newInvoice);

        foreach ($this->taxRecords as $taxRecord) {
            $newTaxRecord = new TaxRecord();
            $newTaxRecord->setInvoice($newInvoice);
            $newTaxRecord->setTaxRate($taxRecord->getTaxRate());
            $newTaxRecord->getSum()->setValue($taxRecord->getSum()->getValue() * -1);
            $newInvoice->getTaxRecords()->add($newTaxRecord);
        }

        /** @var InvoiceItem $invoiceItem */
        foreach ($this->invoiceItems as $invoiceItem) {
            $newInvoiceItem = $invoiceItem->makePartialClone();
            $newInvoiceItem->getSinglePrice()->setValue($invoiceItem->getSinglePrice() * -1);
            $newInvoiceItem->setInvoice($newInvoice);
            $newInvoice->invoiceItems->add($newInvoiceItem);
        }
        $newInvoice->calculateTotal();
        /** @var AccountingRecord $accountingRecord */
        foreach ($this->accountingRecords as $accountingRecord) {
            $newAccountingRecord = clone $accountingRecord;
            $newAccountingRecord->setShouldOrHave('S');
            $newAccountingRecord->setInvoice($newInvoice);
            $newAccountingRecord->setDueDate(null);
            $newAccountingRecord->setBelegfeld2($newInvoice->getNumber()->getCombinedNumber());
            $newAccountingRecord->setText($accountingRecord->getText() . ',Storno ' . $this->getNumber()->getCombinedNumber());
            $newInvoice->getAccountingRecords()->add($newAccountingRecord);
        }

        if ($callback instanceof \Closure) {
            $callback($newInvoice);
        }

        $newInvoice->createDocument($controllerContext, true);
        $this->invoiceRepository->updateAndPersist($newInvoice);

        $this->stornoInvoice = $newInvoice;
        $this->invoiceRepository->updateAndPersist($this);

        return $newInvoice;
    }

    public function __clone()
    {
        $this->number = new NumberingEmbeddable();
        $this->date = new DateTime('now');
        $this->settlementDates->clear();
    }

    public function makePartialClone(): Invoice
    {
        $now = new DateTime('now');
        $clone = new Invoice();
        $clone->getNumber()->setPrefix($this->getNumber()->getPrefix());
        $clone->getNumber()->setPostfix($this->getNumber()->getPostfix());
        $clone->setCustomer(clone $this->getCustomer());
        $clone->setSeller(clone $this->getSeller());
        $clone->setAdditionalInformation($this->additionalInformation);
        $clone->setDate($now);
        $clone->setYear($now->format('Y'));
        $clone->setPeriodOfPerformance(clone $this->getPeriodOfPerformance());
        $clone->setPreText($this->preText);
        $clone->setPostText($this->postText);
        $clone->setAdditionalText($this->additionalText);
        $clone->setChangeable(false);
        $clone->setTotal($this->total);
        $clone->setTotalNoTaxes($this->totalNoTaxes ?? 0.0);
        return $clone;
    }

    public function makeBankTransferDocument()
    {
        if ($this->isChangeable()) {
            throw new \InvalidArgumentException('Only fixed invoices can get these documents');
        }

        /** @var SettlementDate $date */
        foreach ($this->getSettlementDates() as $date) {
            $d1 = new BankTransferDocument();
            $d1->setInvoice($this);
            $d1->setSettlementDate($date);
            $d1->setTitle($date->getComment());
            $d1->setToBePrinted(true);
            $d1->makeDocument();
        }
    }

    /**
     * @ORM\PrePersist()
     * @return void
     */
    public function prePersistHandler(): void
    {
        $this->addressEmbeddableService->updateFields($this->getSeller());
        $this->addressEmbeddableService->updateFields($this->getCustomer());
    }
}
