<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190531052737 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->connection->transactional(function () {
            $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice ADD originalresource VARCHAR(40) DEFAULT NULL, ADD address LONGTEXT DEFAULT NULL, ADD changeable TINYINT(1) NOT NULL, ADD total DOUBLE PRECISION NOT NULL, CHANGE number number INT DEFAULT NULL');
        });
        try {
            $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice ADD CONSTRAINT FK_CBA55464E59BB9C FOREIGN KEY (originalresource) REFERENCES neos_flow_resourcemanagement_persistentresource (persistence_object_identifier)');
        } catch (\Exception $e) {
            $this->write('> Skipping foreign key creation for kaystrobach_invoice_domain_model_invoice.originalresource' . $e->getMessage());
        }

        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBA55464E59BB9C ON kaystrobach_invoice_domain_model_invoice (originalresource)');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     * @throws \Doctrine\DBAL\Migrations\IrreversibleMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->throwIrreversibleMigrationException();
    }
}
