<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190802215734 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_dailyclosing CHANGE originalresource originalresource VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_dailyclosing_download DROP INDEX UNIQ_E566EE37D3656A4, ADD INDEX IDX_E566EE37D3656A4 (account)');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_dailyclosing_download CHANGE dailyclosing dailyclosing VARCHAR(40) DEFAULT NULL, CHANGE account account VARCHAR(40) DEFAULT NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     * @throws \Doctrine\DBAL\Migrations\IrreversibleMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->throwIrreversibleMigrationException();
    }
}
