<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20191212085345 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql',
            'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice ADD stornoinvoice VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice ADD CONSTRAINT FK_CBA55468EF5FB03 FOREIGN KEY (stornoinvoice) REFERENCES kaystrobach_invoice_domain_model_invoice (persistence_object_identifier)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBA55468EF5FB03 ON kaystrobach_invoice_domain_model_invoice (stornoinvoice)');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql',
            'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice DROP FOREIGN KEY FK_CBA55468EF5FB03');
        $this->addSql('DROP INDEX UNIQ_CBA55468EF5FB03 ON kaystrobach_invoice_domain_model_invoice');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice DROP stornoinvoice');

    }
}
