<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190110044335 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_comment (persistence_object_identifier VARCHAR(40) NOT NULL, date DATETIME NOT NULL, comment TEXT(21844) DEFAULT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_invoiceitem (persistence_object_identifier VARCHAR(40) NOT NULL, invoice VARCHAR(40) DEFAULT NULL, amount INT NOT NULL, unit VARCHAR(255) NOT NULL, tax DOUBLE PRECISION NOT NULL, singleprice DOUBLE PRECISION NOT NULL, name VARCHAR(255) NOT NULL, description TEXT(21844) DEFAULT NULL, total DOUBLE PRECISION NOT NULL, discount DOUBLE PRECISION NOT NULL, INDEX IDX_DC8FC4BD90651744 (invoice), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_settlementdate (persistence_object_identifier VARCHAR(40) NOT NULL, invoice VARCHAR(40) DEFAULT NULL, duedate DATETIME NOT NULL, amount DOUBLE PRECISION NOT NULL, comment TEXT(21844) DEFAULT NULL, INDEX IDX_EEDB274A90651744 (invoice), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_invoice (persistence_object_identifier VARCHAR(40) NOT NULL, numberprefix VARCHAR(255) NOT NULL, number INT DEFAULT NULL, currency VARCHAR(255) NOT NULL, deptor TEXT(65532) DEFAULT NULL, deptornumber VARCHAR(255) NOT NULL, additionalinformation TEXT(65532) DEFAULT NULL, date DATETIME NOT NULL, year VARCHAR(255) NOT NULL, periodofperformancecomment TEXT(65532) DEFAULT NULL, additionaltext TEXT(65532) DEFAULT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoiceitem ADD CONSTRAINT FK_DC8FC4BD90651744 FOREIGN KEY (invoice) REFERENCES kaystrobach_invoice_domain_model_invoice (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_settlementdate ADD CONSTRAINT FK_EEDB274A90651744 FOREIGN KEY (invoice) REFERENCES kaystrobach_invoice_domain_model_invoice (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoiceitem DROP FOREIGN KEY FK_DC8FC4BD90651744');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_settlementdate DROP FOREIGN KEY FK_EEDB274A90651744');
        $this->addSql('DROP TABLE kaystrobach_invoice_domain_model_comment');
        $this->addSql('DROP TABLE kaystrobach_invoice_domain_model_invoiceitem');
        $this->addSql('DROP TABLE kaystrobach_invoice_domain_model_settlementdate');
        $this->addSql('DROP TABLE kaystrobach_invoice_domain_model_invoice');
    }
}
