<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20201026182711 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_invoice_taxrecord (persistence_object_identifier VARCHAR(40) NOT NULL, invoice VARCHAR(40) DEFAULT NULL, taxrate DOUBLE PRECISION NOT NULL, sum DOUBLE PRECISION NOT NULL, INDEX IDX_C41DF4F490651744 (invoice), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice_taxrecord ADD CONSTRAINT FK_C41DF4F490651744 FOREIGN KEY (invoice) REFERENCES kaystrobach_invoice_domain_model_invoice (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('DROP TABLE kaystrobach_invoice_domain_model_invoice_taxrecord');
    }
}
