<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20210804114056 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_invoice_banktransferdocument (persistence_object_identifier VARCHAR(40) NOT NULL, originalresource VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, tobeprinted TINYINT(1) NOT NULL, creationdate DATETIME NOT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_1E4526BE4E59BB9C (originalresource), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice_banktransferdocument ADD CONSTRAINT FK_1E4526BE4E59BB9C FOREIGN KEY (originalresource) REFERENCES neos_flow_resourcemanagement_persistentresource (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('DROP TABLE kaystrobach_invoice_domain_model_invoice_banktransferdocument');
    }
}
