<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20201230092902 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        // update belegfeld 1 for all invoices to reproduce old behaviour
        $this->addSql('
            UPDATE
                kaystrobach_invoice_domain_model_accountingrecord record
            LEFT JOIN kaystrobach_invoice_domain_model_invoice as parent_invoice
                ON record.invoice = parent_invoice.persistence_object_identifier
            LEFT JOIN kaystrobach_invoice_domain_model_invoice as  initial_invoice
                ON parent_invoice.persistence_object_identifier = initial_invoice.stornoinvoice
            SET
                belegfeld1 = parent_invoice.numbercomplete
        ');
        // update belegfeld 2 for all invoices having a duedate to reproduce old behaviour
        $this->addSql('
            UPDATE
                kaystrobach_invoice_domain_model_accountingrecord record
            LEFT JOIN kaystrobach_invoice_domain_model_invoice as parent_invoice
                ON record.invoice = parent_invoice.persistence_object_identifier
            LEFT JOIN kaystrobach_invoice_domain_model_invoice as  initial_invoice
                ON parent_invoice.persistence_object_identifier = initial_invoice.stornoinvoice
            SET
                belegfeld2 = DATE_FORMAT(record.duedate, "%d%m%y")
            WHERE
                record.duedate IS NOT NULL
        ');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
    }
}
