<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190802212414 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_dailyclosing (persistence_object_identifier VARCHAR(40) NOT NULL, originalresource VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, sum DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_3DB34F564E59BB9C (originalresource), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kaystrobach_invoice_domain_model_dailyclosing_download (persistence_object_identifier VARCHAR(40) NOT NULL, dailyclosing VARCHAR(40) DEFAULT NULL, account VARCHAR(40) DEFAULT NULL, INDEX IDX_E566EE32D4F3B9B (dailyclosing), UNIQUE INDEX UNIQ_E566EE37D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_dailyclosing ADD CONSTRAINT FK_3DB34F564E59BB9C FOREIGN KEY (originalresource) REFERENCES neos_flow_resourcemanagement_persistentresource (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_dailyclosing_download ADD CONSTRAINT FK_E566EE32D4F3B9B FOREIGN KEY (dailyclosing) REFERENCES kaystrobach_invoice_domain_model_dailyclosing (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_dailyclosing_download ADD CONSTRAINT FK_E566EE37D3656A4 FOREIGN KEY (account) REFERENCES neos_flow_security_account (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws \Doctrine\DBAL\Migrations\AbortMigrationException
     * @throws \Doctrine\DBAL\Migrations\IrreversibleMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->throwIrreversibleMigrationException();
    }
}
