<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20210805104634 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice ADD dtype VARCHAR(255) NOT NULL');

        // @todo move into obos / fluege
        $this->addSql('UPDATE kaystrobach_invoice_domain_model_invoice SET dtype="kaystrobach_invoice_invoice"');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice MODIFY COLUMN dtype VARCHAR(255) AFTER persistence_object_identifier');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice DROP dtype');
    }
}
