<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20210805180913 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice_banktransferdocument ADD settlementdate VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice_banktransferdocument ADD CONSTRAINT FK_1E4526BEC7E72B90 FOREIGN KEY (settlementdate) REFERENCES kaystrobach_invoice_domain_model_settlementdate (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_1E4526BEC7E72B90 ON kaystrobach_invoice_domain_model_invoice_banktransferdocument (settlementdate)');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice CHANGE dtype dtype VARCHAR(255) NOT NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice CHANGE dtype dtype VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice_banktransferdocument DROP FOREIGN KEY FK_1E4526BEC7E72B90');
        $this->addSql('DROP INDEX IDX_1E4526BEC7E72B90 ON kaystrobach_invoice_domain_model_invoice_banktransferdocument');
        $this->addSql('ALTER TABLE kaystrobach_invoice_domain_model_invoice_banktransferdocument DROP settlementdate');
    }
}
